### ISSUE TITLE
Uncaught Error: Minified React error #130

### ISSUE THREAD

**Issue by DrKJeff16** [atom-ide-community/atom-ide-console#26]
[Enter steps to reproduce:]

1. Ctrl+Shift+P -> Debugger: `Show`

**Atom**: 1.59.0-beta0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-ide-console](https://github.com/atom-ide-community/atom-ide-console) package 0.0.2

### Stack Trace

Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

```
At C:\Users\maxus\.atom\packages\atom-ide-console\node_modules\@atom-ide-community\nuclide-commons-ui\node_modules\react-dom\cjs\react-dom.production.min.js:243

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Vg (/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:280:177)
    at /packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:149:163
    at fi (/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:176:186)
    at ck (/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:270:437)
    at bk (/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:250:347)
    at ak (/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:250:278)
    at Tj (/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:250:138)
    at Lj (/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:243:163)
    at Jg (/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:237:175)
    at lk (/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:285:27)
    at /packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:289:301
    at Xj (/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:244:244)
    at tk (/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:289:287)
    at Object.exports.render (/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:296:69)
    at HTMLElement.connectedCallback (/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/ReactMountRootElement.js:64:23)
    at HTMLElement.activeItemChanged (/app.asar/src/pane-element.js:152:22)
    at Function.simpleDispatch (~/AppData/Local/atom-beta/app-1.59.0-beta0/resources/app/static/<embedded>:11:1187446)
    at Emitter.emit (~/AppData/Local/atom-beta/app-1.59.0-beta0/resources/app/static/<embedded>:11:1188887)
    at Pane.setActiveItem (~/AppData/Local/atom-beta/app-1.59.0-beta0/resources/app/static/<embedded>:11:459446)
    at Pane.activateItem (~/AppData/Local/atom-beta/app-1.59.0-beta0/resources/app/static/<embedded>:11:461694)
    at DebuggerLayoutManager._appendItemToDock (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:323:20)
    at DebuggerLayoutManager._addPaneContainerToWorkspace (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:648:10)
    at DebuggerLayoutManager.showDebuggerViews (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:593:44)
    at /packages/atom-ide-debugger/dist/main.js:412:24)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom-beta/app-1.59.0-beta0/resources/app/static/<embedded>:11:352663)
    at Object.didConfirmSelection (~/AppData/Local/atom-beta/app-1.59.0-beta0/resources/app/static/<embedded>:11:687705)
    at SelectListView.confirmSelection (~/AppData/Local/atom-beta/app-1.59.0-beta0/resources/app/static/<embedded>:14:556054)
    at HTMLDivElement.core:confirm (~/AppData/Local/atom-beta/app-1.59.0-beta0/resources/app/static/<embedded>:14:550933)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom-beta/app-1.59.0-beta0/resources/app/static/<embedded>:11:352663)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom-beta/app-1.59.0-beta0/resources/app/static/<embedded>:11:1228249)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom-beta/app-1.59.0-beta0/resources/app/static/<embedded>:11:1224383)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom-beta/app-1.59.0-beta0/resources/app/static/<embedded>:11:286651)
```

### Commands

```
     -0:50.5.0 intentions:highlight (input.hidden-input)
     -0:50.2.0 command-palette:toggle (input.hidden-input)
     -0:48.6.0 core:move-down (input.hidden-input)
     -0:48.1.0 core:confirm (input.hidden-input)
     -0:48.1.0 debugger:show (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-html-preview 0.2.7 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-console 0.0.2 
atom-ide-datatip 0.25.0 
atom-ide-debugger 0.0.3 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
atom-json 0.6.0 
atom-latex 0.9.1 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-visual-studio-code-ui 2.1.0 
autoclose-html 0.23.0 
bracket-colorizer 1.4.0 
busy 0.7.0 
busy-signal 2.0.1 
dash-syntax 0.4.2 
dash-ui 0.4.4 
dracula-syntax 3.0.2 
dracula-ui 0.6.0 
emmet 2.4.3 
file-icons 2.1.47 
gpp-compiler 3.0.7 
html-to-css 0.2.2 
ide-cpp 0.1.0 
ide-csharp 0.6.2 
ide-html 0.7.0 
ide-java 0.9.1 
ide-json 0.2.1 
ide-python 1.9.7 
intentions 2.1.1 
java-import-wiz 0.5.0 
java-plus 0.1.0 
language-latex 1.2.0 
latex 0.50.2 
linter 3.4.0 
linter-gcc 0.9.0 
linter-javac 1.10.0 
linter-markdown 5.2.11 
linter-pylint 2.1.1 
linter-ui-default 3.4.1 
markdown-to-pdf 0.1.1 
monokai 0.28.0 
pp 0.0.1 
pp-markdown 0.0.2 
python-indent 1.2.6 
script 3.32.2 
seti-syntax 1.2.0 
seti-ui 1.11.0 
spaceduck-syntax 0.1.0 
spaceduck-ui 0.3.0 
spacemacs-dark-syntax 0.5.0 
vim-mode-plus 1.36.7 
vim-modeline 0.5.2 
```

**Comment by kylestratis** [comment]
Seeing this as well

```
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Vg (/Users/kylestratis/.atom/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:280:177)
    at /Users/kylestratis/.atom/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:149:163
    at fi (/Users/kylestratis/.atom/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:176:186)
    at ck (/Users/kylestratis/.atom/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:270:437)
    at bk (/Users/kylestratis/.atom/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:250:347)
    at ak (/Users/kylestratis/.atom/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:250:278)
    at Tj (/Users/kylestratis/.atom/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:250:138)
    at Lj (/Users/kylestratis/.atom/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:243:163)
    at Jg (/Users/kylestratis/.atom/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:237:175)
    at lk (/Users/kylestratis/.atom/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:285:27)
    at /Users/kylestratis/.atom/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:289:301
    at Xj (/Users/kylestratis/.atom/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:244:244)
    at tk (/Users/kylestratis/.atom/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:289:287)
    at Object.exports.render (/Users/kylestratis/.atom/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/node_modules/react-dom/cjs/react-dom.production.min.js:296:69)
    at HTMLElement.connectedCallback (/Users/kylestratis/.atom/packages/atom-ide-console/node_modules/@atom-ide-community/nuclide-commons-ui/ReactMountRootElement.js:64:23)
    at HTMLElement.activeItemChanged (/Users/kylestratis/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:152:22)
    at Function.simpleDispatch (/Users/kylestratis/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (/Users/kylestratis/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1188366)
    at Pane.setActiveItem (/Users/kylestratis/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:458925)
    at Pane.activateItem (/Users/kylestratis/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:461173)
    at Workspace.open (/Users/kylestratis/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:434844)
```
